export const CamposVistoria = [
  'Farol',
  'Pisca',
  'Lanterna Dianteira',
  'Lanterna Traseira',
  'Roda Dianteira',
  'Roda Traseira',
  'Pneu Dianteiro',
  'Pneu Traseiro',
  'Calota Dianteira',
  'Calota Traseira',
  'Espelho Retrovisor',
];
export const CamposForm = [
  'Luz de Placa',
  'Luz de Ré',
  'Luz Interna',
  'Bateria',
  'Extintor',
  'Estepe',
  'Macaco',
  'Chave de Roda',
  'Rádio',
  'Painel',
  'Retrovisor Interno',
  'Luminoso(Giro)',
  'Sirene',
  'Antena',
  'Painel de Instrumentos',
  'Estojo de Ferramentas',
  'Módulo de Controle(Giro/Sirene)',
  'Documento de Licenciamento',
  'Cartão de Abastecimento',
  'Documento de Lincenciamento',
  'Antena de Segurança',
  'Nível de Água no Reservatório',
];
